export const sendError = (message: string) => {
  try {
  } catch (e) {}
};
